version: "3"

services:

  nexus:
    build: ./nexus-oss
    ports:
      - "8081:8081"
      - "5000:5000"
    volumes:
      - ./nexus-data:/nexus-data
    container_name: nexus
    restart: always
